# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: asterisk_service.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'asterisk_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x61sterisk_service.proto\x12\x10\x61sterisk_service\"\\\n\x11\x43\x61llStreamRequest\x12\x0f\n\x07\x63\x61ll_id\x18\x01 \x01(\t\x12\x15\n\x0b\x61udio_chunk\x18\x02 \x01(\x0cH\x00\x12\x14\n\nevent_type\x18\x03 \x01(\tH\x00\x42\t\n\x07payload\"v\n\x12\x43\x61llStreamResponse\x12\x0f\n\x07\x63\x61ll_id\x18\x01 \x01(\t\x12\x15\n\x0b\x61udio_chunk\x18\x02 \x01(\x0cH\x00\x12\x17\n\rtext_response\x18\x03 \x01(\tH\x00\x12\x14\n\nevent_type\x18\x04 \x01(\tH\x00\x42\t\n\x07payload\"$\n\x11HangupCallRequest\x12\x0f\n\x07\x63\x61ll_id\x18\x01 \x01(\t\"6\n\x12HangupCallResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xcf\x01\n\x11\x41steriskConnector\x12\x61\n\x10HandleCallStream\x12#.asterisk_service.CallStreamRequest\x1a$.asterisk_service.CallStreamResponse(\x01\x30\x01\x12W\n\nHangupCall\x12#.asterisk_service.HangupCallRequest\x1a$.asterisk_service.HangupCallResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'asterisk_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CALLSTREAMREQUEST']._serialized_start=44
  _globals['_CALLSTREAMREQUEST']._serialized_end=136
  _globals['_CALLSTREAMRESPONSE']._serialized_start=138
  _globals['_CALLSTREAMRESPONSE']._serialized_end=256
  _globals['_HANGUPCALLREQUEST']._serialized_start=258
  _globals['_HANGUPCALLREQUEST']._serialized_end=294
  _globals['_HANGUPCALLRESPONSE']._serialized_start=296
  _globals['_HANGUPCALLRESPONSE']._serialized_end=350
  _globals['_ASTERISKCONNECTOR']._serialized_start=353
  _globals['_ASTERISKCONNECTOR']._serialized_end=560
# @@protoc_insertion_point(module_scope)
